### ISSUE TITLE
使用这插件是不是只能下载使用啊

### ISSUE THREAD

**Issue by 982991084** [MobClub/MobLink-For-Flutter#2]
能给一个完成的配置过程吗？

**Comment by lishuzhi1121** [comment]
你好，可以配置插件使用，参考： https://pub.dev/packages/moblink#-installing-tab- 另外，这个插件因为是我们Mob官方提供的，所以引用插件之后还需要对项目进行一些配置，iOS可以参考：http://wiki.mob.com/moblink-ios-doc/  安卓可以参考：http://wiki.mob.com/moblinkandroidgradle3-x/  包括前端网页也是需要集成的，Web参考：http://wiki.mob.com/moblink-web-doc/ 如有任何问题或是需要指导可以直接联系qq 493231305

**Comment by lishuzhi1121** [comment]
感谢您的支持🙏我们全力为您服务
